### ISSUE TITLE
Bug. Both `linux` & `linuxmusl` are installed

### ISSUE THREAD

**Issue by o-alexandrov** [pH200/sharp-layer#2]
Steps to reproduce:
- download latest release from this repo
- observe both `linux` & `linuxmusl` are installed

Shouldn't only `linux` be installed under `@img`?

**Comment by pH200** [comment]
Thank you for pointing out the issue. This is fixed by 5d980eb and the [latest release](https://github.com/pH200/sharp-layer/releases/tag/0.33.1).
Additionally, npm currently does not support specifying libc. I'll update the script once the following issues are addressed.
https://github.com/npm/cli/pull/6914
https://github.com/lovell/sharp/issues/3873

**Comment by Yashneel12345** [comment]
how to install
